version: "2"
services:
  repl:
    image: "clojure:lein-2.8.3"
    command: "lein test"
    user: "${UID}:${GID}"
    working_dir: ${PWD}
    volumes:
      - ~/.m2/repository:/root/.m2/repository
      - /etc/passwd:/etc/passwd
      - ~/:/home/${USR}
    environment:
      TERM: xterm
