version: "2"
services:
  repl:
    tty: true
    image: "clojure:lein-2.8.3"
    command: "lein repl :start :port 30000"
    user: "${UID}:${GID}"
    ports:
      - "30000:30000"
    working_dir: ${PWD}
    volumes:
      - ~/.m2/repository:/root/.m2/repository
      - /etc/passwd:/etc/passwd
      - ~/:/home/${USR}
    environment:
      TERM: xterm
    extra_hosts:
    - "host.docker.internal:host-gateway"
