version: "2"
services:
  app:
    image: "clojure:lein-2.8.3"
    command: "lein trampoline ring server-headless 33333"
    user: "${UID}:${GID}"
    ports:
      - "33333:33333"
    working_dir: ${PWD}
    volumes:
      - ~/.m2/repository:/root/.m2/repository
      - ~/:${HOME}
    environment:
      TERM: xterm
      # LEIN_FAST_TRAMPOLINE: y
    extra_hosts:
    - "host.docker.internal:host-gateway"
